### ISSUE TITLE
Paper spigot 1.12.2 fails to load plugin

### ISSUE THREAD

**Issue by RealmportalMC** [SugarCaney/CrystalQuest#2]
```
[22:14:54] [Server thread/ERROR]: Error occurred while enabling CrystalQuest vv1.3 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(Ljava/io/InputStream;)Lorg/bukkit/configuration/file/YamlConfiguration;
	at nl.sugcube.crystalquest.CrystalQuest.reloadData(CrystalQuest.java:283) ~[?:?]
	at nl.sugcube.crystalquest.CrystalQuest.onEnable(CrystalQuest.java:85) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1350]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12.2.jar:git-Paper-1350]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [patched_1.12.2.jar:git-Paper-1350]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:387) [patched_1.12.2.jar:git-Paper-1350]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:336) [patched_1.12.2.jar:git-Paper-1350]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) [patched_1.12.2.jar:git-Paper-1350]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) [patched_1.12.2.jar:git-Paper-1350]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) [patched_1.12.2.jar:git-Paper-1350]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:292) [patched_1.12.2.jar:git-Paper-1350]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1350]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
[22:14:54] [Server thread/INFO]: [CrystalQuest] Disabling CrystalQuest vv1.3
[22:14:54] [Server thread/ERROR]: Error occurred while disabling CrystalQuest vv1.3 (Is it up to date?)
```

**Comment by SugarCaney** [comment]
This has probably something to do with using wrong mc versions.

CQ 1.3 is developed for MC 1.11, and will work for that version only. Make sure you use the right one.

Bit too late, but putting it here anyway for archiving purposes.
